### ISSUE TITLE
Coordinate system of the exported 3D model

### ISSUE THREAD

**Issue by Zumbalamambo** [laanlabs/3dScannerApp_samples#1]
Thank you for the amazing application.  what is the coordinate system of the exported 3d model? (textured_output.obj)

**Comment by cclaan** [comment]
Y-up , right handed, see:
https://developer.apple.com/documentation/scenekit/organizing_a_scene_with_nodes

"SceneKit uses a right-handed coordinate system where (by default) the direction of view is along the negative z-axis"

**Comment by Zumbalamambo** [comment]
thank you! Would be nice to see a superimposed image and point cloud via open3d :) Tried my best but couldn't be able to superimpose efficiently.

**Comment by cclaan** [comment]
Can you point to a similar example with open3d? I've used it for rendering point clouds but not 2d images.
